
cluster.name: guangxian_game
node.name: node_152
node.master: true
node.data: true

index.number_of_shards: 3
index.number_of_replicas: 1
index.cache.field.type: soft
index.cache.field.max_size: 50000
index.cache.field.expire: 10m


transport.tcp.compress: true
http.cors.allow-origin: "/.*/"
http.cors.enabled: true

bootstrap.mlockall: true
indices.cache.filter.size: 20%
indices.fielddata.cache.size: 20%
indices.fielddata.cache.expire: -1
indices.memory.index_buffer_size: 50%
index.refresh_interval: 30s
index.translog.flush_threshold_ops: 50000
index.store.compress.stored: true

indices.store.throttle.type: merge
indices.store.throttle.max_bytes_per_sec: 500mb

discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: ["182.92.11.137"]
