
nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "jetty"
    volumes:
      - ~/opt/htdocs/Dockerfiles/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/opt/logs/nginx:/etc/nginx/logs
    restart: always
jetty:
    build: ./jetty
    ports:
      - "8080:8080"
    links:
      - "mysql"
      - "elasticsearch"
    volumes:
     - ~/opt/jenkins/mnt/jenkins_home/workspace/game-server/target/game-server.war:/opt/jetty/webapps/game-server.war
     #- ~/opt/htdocs/Dockerfiles/jetty/webapps/game-server.war:/opt/jetty/webapps/game-server.war
     - ~/opt/logs/jetty:/opt/jetty/logs
    restart: always
mysql:
    build: ./mysql
    ports:
      - "3305:3306"
    volumes:
      - ~/opt/htdocs/Dockerfiles/mysql/game_server.sql:/docker-entrypoint-initdb.d/game_server.sql
      - ~/opt/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: game_server
    restart: always
elasticsearch:
    build: ./elasticsearch
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ~/opt/htdocs/Dockerfiles/elasticsearch/bin/elasticsearch.in.sh:/usr/share/elasticsearch/bin/elasticsearch.in.sh
      - ~/opt/htdocs/Dockerfiles/elasticsearch/config:/usr/share/elasticsearch/config
      - ~/opt/data/elasticsearch/data:/usr/share/elasticsearch/data
    mem_limit: 2g
    restart: always
    privileged: true
redis:
    build: ./redis
    ports:
      - "6378:6379"
    restart: always
logstashindexerkds:
    build: ./logstash
    volumes:
        - ~/opt/htdocs/Dockerfiles/logstash/kds/index.conf:/opt/logstash/conf/index.conf
    links:
        - "redis"
        - "elasticsearch"
    command: logstash agent  -f /opt/logstash/conf/index.conf
    restart: always
gomiddle:
    build: ./go
    ports: 
        - "8889:8889"
        - "8888:8888"
    volumes:
        - ~/opt/htdocs/Dockerfiles/go/app/server:/go/src/app/server
    working_dir: /go/src/app
    command: ./server
    links:
        - "mysql"
    restart: always
jenkins:
    build: ./jenkins
    ports:
      - "8081:8080"
      - "50001:50000"
    container_name: dockerfiles_jenkins_1
    volumes:
      - ~/opt/jenkins/mnt/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock 
    restart: always
